version: '3.8'
services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: meli
      MONGO_INITDB_ROOT_PASSWORD: PruebaMeli2.
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
  redis:
    image: redis:alpine
    platform: linux/arm64
    ports:
      - 6379:6379
    volumes:
      - ~/apps/redis:/data/cache