spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_l5JMYATiX
  data:
    mongodb:
      uri: mongodb://meli:PruebaMeli2.@localhost:27017/
      database: meli
  main:
    lazy-initialization: true

server:
  port: 8081
  servlet:
    context-path: '/api'